### ISSUE TITLE
New Scripts 

### ISSUE THREAD

**Issue by thizsam** [Bluscream/modest-menu#1]
Hey Dude are You Making some more New Scripts for kiddions ,i checked out those old scripts and was great

**Comment by Bluscream** [comment]
What scripts do you mean?

**Comment by thizsam** [comment]
I mean like some Timechanger , riotmode , ufo spawn on beach , Make all peds to followme many more crazy stuffs

**Comment by Bluscream** [comment]
Sorry, im not taking comissions
